P8015_hw3_dw3093
================
Katherine Wang
2024-10-13

## Question 1

Summary of the dataset This dataset contains `nrow(ny_noaa)` rows and
`ncol(ny_noaa)` columns. This dataset contains 2,595,176 rows and 7
columns The date of observation, ranging from 1981-01-01 to 2010-12-31.

Key variables include: - weather station ID (`id`) - date of observation
(`date`) - precipitation in tenths (mm) (`prcp`) - snowfall (mm)
(`snow`) - snow depth (mm) (`snwd`) - maximum temperature (tenths of
degrees C) (`tmax`) - minimum temperature (tenths of degrees C) (`tmin`)

The `tmax` and `tmin` are set to be character variables, so they need to
converse to numeric variables in the future step.

Through the missing value check, there are a great amount missing (NAs)
values as shown on the table: id date prcp snow snwd tmax tmin 0 0
145838 381221 591786 1134358 1134420

    ##       id                 date                 prcp               snow       
    ##  Length:2595176     Min.   :1981-01-01   Min.   :    0.00   Min.   :  -13   
    ##  Class :character   1st Qu.:1988-11-29   1st Qu.:    0.00   1st Qu.:    0   
    ##  Mode  :character   Median :1997-01-21   Median :    0.00   Median :    0   
    ##                     Mean   :1997-01-01   Mean   :   29.82   Mean   :    5   
    ##                     3rd Qu.:2005-09-01   3rd Qu.:   23.00   3rd Qu.:    0   
    ##                     Max.   :2010-12-31   Max.   :22860.00   Max.   :10160   
    ##                                          NA's   :145838     NA's   :381221  
    ##       snwd             tmax              tmin        
    ##  Min.   :   0.0   Min.   :-389.0    Min.   :-594.0   
    ##  1st Qu.:   0.0   1st Qu.:  50.0    1st Qu.: -39.0   
    ##  Median :   0.0   Median : 150.0    Median :  33.0   
    ##  Mean   :  37.3   Mean   : 139.8    Mean   :  30.3   
    ##  3rd Qu.:   0.0   3rd Qu.: 233.0    3rd Qu.: 111.0   
    ##  Max.   :9195.0   Max.   : 600.0    Max.   : 600.0   
    ##  NA's   :591786   NA's   :1134358   NA's   :1134420

Convert tmax and tmin to numeric variables.

    ## # A tibble: 282 × 2
    ##     snow       n
    ##    <int>   <int>
    ##  1     0 2008508
    ##  2    NA  381221
    ##  3    25   31022
    ##  4    13   23095
    ##  5    51   18274
    ##  6    76   10173
    ##  7     8    9962
    ##  8     5    9748
    ##  9    38    9197
    ## 10     3    8790
    ## # ℹ 272 more rows

The most commonly observed value for snowfall is 0, which indicates that
no snowfall occurred on the majority of days in this dataset that is
2,008,508 observations. This is followed by a large number of NAs,
totaling 381,221 observations, which suggests that snowfall data was not
recorded or available for these entries. Most days in New York State do
not experience snowfall, especially during non-winter months. Therefore,
it is expected that the majority of observations would record 0 for
snowfall, representing days without snow.

``` r
ny_noaa |>
  filter(month==1|month==7)|>
  group_by(id,year,month)|>
  summarise(avg_tmax = mean(tmax, na.rm = TRUE))|>
  ggplot(aes(x = year, y=avg_tmax))+
  geom_point(alpha = .1)+geom_line()+
  facet_grid(.~month)+
  labs( title = "Avg. Max Temperature in Jan and Jul across Years by Station",
    x = "Year",
    y = "avg. max temperature (°C)")+ 
  theme_minimal() + 
  theme(legend.position = "bottom")
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

<img src="p8105_hw3_dw3093_files/figure-gfm/unnamed-chunk-4-1.png" width="90%" />
The two-panel plot shows that avg. max temperatures in January exhibit
more variability across stations and years ranging from about -10°C to
10°C, while July temperatures are relatively stable, consistently around
25°C to 35°C. In January more fluctuations are visible, with few
potential outliers like the lowest temperature is about 13°C in around
1982. July shows minimal variation, the temperature is quite consistency
warm across the years, but still contains few outliers, like the lowest
temperature is about 14°C in around 1988.

``` r
ggp_tmax_tmin=
  ny_noaa|>
  ggplot(aes(x=tmin, y=tmax))+
  geom_hex()+
  labs(
    x = "minimum temperature(°C)",
    y = "maximum temperature(°C)",
    title = "Relationship Between tmax and tmin"
    )+
    theme_minimal()

ggp_snow=
ny_noaa|>
  filter(snow>0, snow<100)|>
  ggplot(aes(x = snow, fill = factor(year))) + 
  geom_density(alpha=.3)+
  labs(title = "Density of Snowfall by Year", x = "snow depth (mm)", y = "year") +
  theme_minimal()

combined_plot =
  ggp_tmax_tmin + ggp_snow

print(combined_plot)
```

<img src="p8105_hw3_dw3093_files/figure-gfm/unnamed-chunk-5-1.png" width="90%" />
The hexbin plot shows a strong positive relationship between tmax and
tmin, with most data points clustered along a diagonal, indicating that
higher minimum temperatures are associated with higher maximum
temperatures. The ridge plot reveals that most snowfall values fall
below 50 mm, with distinct peaks around 25 mm and 75 mm, and some
variation in snowfall distributions across years, though the overall
pattern remains consistent.

## Question 2

\#load, clean, and tidy ‘nhanes_covar’ dataset

\#load, clean, and tidy ‘nhanes_accel’ dataset

\#merge ‘nhanes_covar’ and ‘nhanes_accel’ dataset to ‘merged_df’

``` r
merged_df =
  left_join(covar, accel, by = "seqn")
```

After the data cleaning and merging, the merged_df have 228 observation
and 1445 variables.

\#create a reader-friendly table for the number of men and women in each
education category

``` r
merged_df |>  
  group_by(sex, education) |>
  summarise(count = n(), .groups = "drop") |>
  pivot_wider(
    names_from = education,
    values_from = count
    ) |>
  knitr::kable()
```

| sex    | Less than high school | High school equivalent | More than high school |
|:-------|----------------------:|-----------------------:|----------------------:|
| Male   |                    27 |                     35 |                    56 |
| Female |                    28 |                     23 |                    59 |

The table shows that 27 males and 28 females have less than a high
school education, 35 males and 23 females have a high school equivalent
education, and 56 males and 59 females have more than a high school
education.

For the “less than a high school education” and “more than a high school
education” categories, the number between males and females is
relatively balanced, but for the “high school equivalent education”
category, there are much fewer males than females.

\#create a visualization of the age distributions for men and women in
each education category

``` r
merged_df |>
  ggplot(aes(x = sex, y = age, fill = education)) +
  geom_boxplot()+
  facet_grid(. ~ education) +
  labs(title = "Age Distribution by Gender and Education", 
       x = "Sex", 
       y = "Age (year)")+
   theme_minimal()
```

<img src="p8105_hw3_dw3093_files/figure-gfm/unnamed-chunk-10-1.png" width="90%" />
The box plot shows that participants with less than a high school
education are older, with both males and females having a similar median
age around 60 years and a narrow age range. In the high school
equivalent category, males tend to have a slightly higher median age
compared to females, and both genders show a broader age range, with
males having a particularly widespread from their 20s to 80s. In the
more than high school category, males and females have similar age
distributions, both with a median age of around 60 years, though females
exhibit a slightly broader range.

# Total Activity by Participant

``` r
merged_df |> 
  mutate(
    total_activity = rowSums(across(starts_with("min")), na.rm = TRUE)
  ) |>
  select(seqn, sex, age, bmi, education, total_activity) |> 
  ggplot(aes(x = age, y = total_activity, color = sex)) + 
  geom_point(alpha=.5) + 
  geom_smooth(method = "loess", se = FALSE) + 
  facet_wrap(~education) + 
  labs(
    title = "Total Activity by Age, Gender, and Education", 
    x = "Age", 
    y = "Total Activity"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom"
  )
```

    ## `geom_smooth()` using formula = 'y ~ x'

<img src="p8105_hw3_dw3093_files/figure-gfm/unnamed-chunk-11-1.png" width="90%" />
The plot shows that total activity for females tends to be higher at
younger ages, particularly in the “high school equivalent” and “more
than high school” categories, but their activity levels decline more
steeply as they age, especially after age 60. In contrast, males show a
more gradual decline in activity over time compared to females. In the
“less than high school” group, the gap between male and female activity
levels is smaller, and both sexes experience a sharp decline in total
activity as they approach older age. In the “high school equivalent” and
“more than high school” groups, females have notably higher activity in
their 20s and 30s but diminish by age 60, where male and female activity
levels converge and decline together.
